project:
  type: website

website:
  title: "ISSS608-Visual Analytics and Applications"
  navbar:
    title: false
    search: true
    background: "#2c3e50"
    collapse-below: lg      
    left: 
      - icon: house-fill
        href: index.qmd
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd"
          - text: "Hands-on Exercise 3a"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.qmd"
          - text: "Hands-on_Exercise 3b"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.qmd"
          - text: "Hands-on Exercise 4a"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.qmd"
          - text: "Hands-on Exercise 4b"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.qmd"
          - text: "Hands-on Exercise 4c"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.qmd"
          - text: "Hands-on Exercise 4d"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.qmd"
          - text: "Hands-on Exercise 5a"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.qmd"
          - text: "Hands-on Exercise 5b"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.qmd"
          - text: "Hands-on Exercise 5c"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.qmd"
          - text: "Hands-on Exercise 5d"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.qmd"
          - text: "Hands-on Exercise 5e"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.qmd"   
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.qmd" 
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd"
    right:
      - icon: github
        href: https://github.com/keaidewoq
      - icon: linkedin
        href: https://linkedin.com/in/xuqianqian0706
      - text: "About"
        href: about.qmd

  page-footer:
    left: "Â© 2026 Xu Qianqian"
    right: 
      - text: "Made with Quarto"
        icon: heart-fill
  
  back-to-top-navigation: true
  
format:
  html:
    theme: 
      light: flatly
    css: styles.css
    google-resources: true
    mainfont: "Fredoka" 
    toc: true
    toc-location: right
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    page-layout: full

editor: visual